#ifndef CONTROLLER_H_
#define CONTROLLER_H_

#include "../model/maze.h"

namespace maze {
  class Controller {
    public:
      // will be generated by compiler ?
      Controller() {};
      /* ~Controller() {}; */
      Controller(const Controller& other) : m{other.m} {}

      void ReadMaze(const std::string& path);
      void print() {m.print();}

      std::size_t Size() const noexcept;
      const std::vector<std::vector<bool>>& GetVerticalWalls() const noexcept;
      const std::vector<std::vector<bool>>& GetHorizontalWalls() const noexcept;

    private:
      Maze m;
  };
} // namespace maze

#endif // CONTROLLER_H_
